development:
  strategy: oauth
  oauth_consumer_key: 2jTuuEtYXO9NwHZ2BWMA
  oauth_consumer_secret: diKHOJ6dEd83ycComonK5CH2TRrt4dyHusU65uV8
  base_url: "https://twitter.com"
  authorize_path: "/oauth/authenticate"
  api_timeout: 10
  remember_for: 14 # days
  oauth_callback: "http://localhost:3000/oauth_callback"
test:
  strategy: oauth
  oauth_consumer_key: 2jTuuEtYXO9NwHZ2BWMA
  oauth_consumer_secret: diKHOJ6dEd83ycComonK5CH2TRrt4dyHusU65uV8
  base_url: "https://twitter.com"
  authorize_path: "/oauth/authenticate"
  api_timeout: 10
  remember_for: 14 # days
  oauth_callback: "http://localhost:3000/oauth_callback"
production:
  strategy: oauth
  oauth_consumer_key: IJb8P1paSoDBdTBkULA8RQ
  oauth_consumer_secret: XHPZGkBvWsEPz4M7YlIHMiGoK8ipVCOba56jHIpE 
  authorize_path: "/oauth/authenticate"
  base_url: "https://twitter.com"
  api_timeout: 10
  remember_for: 14 # days
  oauth_callback: "http://go.goupon.com/oauth_callback"